# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Stephinlinexo
email: stephinlinexo@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: stephinline
github_username:  jekyll

# Build settings
markdown: kramdown
remote_theme: y7kim/agency-jekyll-theme
plugins:
 - jekyll-feed
 - jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Team names, titles and social links
people:
- name: Stephanie Santana
  pic: 1
  position: Founder & CEO
  social:
    - title: instagram
      url: https://www.instagram.com/stephinline
    - title: youtube
      url: https://www.youtube.com/channel/UC_nmeLMKpNunsWJO6g57YQA
    - title: reddit
      url: https://www.reddit.com/r/Stephinline/

- name: Rosmon Sidhik
  pic: 2
  position: VP, Product & Engg
  social:
    - title: twitter
      url: https://twitter.com/rosmons
    - title: instagram
      url: https://www.instagram.com/rosmonsidhik/
    - title: linkedin
      url: https://www.linkedin.com/in/rosmons/

- name: Chris Puccetti
  pic: 4
  position: Developer
  social:
    - title: instagram
      url: https://www.instagram.com/chrisdavilllager/
    - title: github
      url: https://github.com/ChrisDaVillager
    - title: linkedin
      url: https://www.linkedin.com/in/chris-puccetti/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/stephinline
  - title: youtube
    url: https://www.youtube.com/channel/UC_nmeLMKpNunsWJO6g57YQA
  - title: reddit
    url: https://www.reddit.com/r/Stephinline/

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210
